#!/usr/bin/env bash
# Phase 265: Audit Export Generation, Evidence Packaging, Compliance Reports
# Track 18 - Compliance

compliance_audit_export() {
    local domain="${1:?Usage: compliance_audit_export <domain>}"

    source "$(dirname "$0")/../core/core.sh"

    local output_dir="$OUTPUT_DIR/$domain/recon_$TIMESTAMP"
    local phase_dir="$output_dir/compliance_audit_export"
    mkdir -p "$phase_dir/audit_package"

    log "INFO" "[AUDIT_EXPORT] Starting audit export generation for $domain"

    local compliance_report="$phase_dir/compliance_report.md"

    local count=0

    log "INFO" "[AUDIT_EXPORT] Packaging existing compliance findings"
    {
        echo "# Compliance Audit Report - $domain"
        echo ""
        echo "**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "**Domain:** $domain"
        echo "**Scan Timestamp:** $TIMESTAMP"
        echo ""
        echo "## Findings Summary"
        echo ""

        local finding_count
        finding_count=$(find "$output_dir" -name "*.json" -path "*/compliance_*" 2>/dev/null | wc -l || echo "0")
        echo "- Total compliance phases with output: $finding_count"
        echo ""

        echo "## Packaged Evidence"
        echo ""

        for comp_dir in "$output_dir"/compliance_*/; do
            if [ -d "$comp_dir" ]; then
                local phase_name
                phase_name=$(basename "$comp_dir")
                echo "### $phase_name"
                echo ""
                local files
                files=$(ls "$comp_dir" 2>/dev/null || true)
                for f in $files; do
                    if [ -f "$comp_dir/$f" ]; then
                        echo "- $f"
                        cp "$comp_dir/$f" "$phase_dir/audit_package/${phase_name}_${f}" 2>/dev/null || true
                        count=$((count + 1))
                    fi
                done
                echo ""
            fi
        done

        echo "## Audit Package Contents"
        echo ""
        echo "All evidence files have been consolidated into the \`audit_package/\` directory."
        echo ""
        echo "---"
        echo "*Report generated by DarkRecon compliance audit export*"
    } > "$compliance_report"

    if tool_available "tar"; then
        log "INFO" "[AUDIT_EXPORT] Creating compressed audit archive"
        tar -czf "$phase_dir/audit_package.tar.gz" -C "$phase_dir" audit_package 2>/dev/null || true
        count=$((count + 1))
    fi

    echo "$count" > "$phase_dir/count.txt"
    py_log "INFO" "audit_export_complete" "Audit export complete: $count files packaged"
    log "INFO" "[AUDIT_EXPORT] Completed: $count files in audit package"

    write_finding "{\"type\":\"compliance_audit_export\",\"severity\":\"info\",\"count\":$count,\"phase\":\"compliance_audit_export\"}" \
        "$output_dir/findings.jsonl" 2>/dev/null || true

    write_asset "$phase_dir" "domain" "$domain" "target"
    write_endpoint "$phase_dir" "file://$phase_dir/audit_package.tar.gz" "READ" "Audit package archive"

    return 0
}
